version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "/api"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "/app"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "/shared"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "/infra"
    schedule:
      interval: "monthly"
